myapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),

]

polls/urls.py
from django.urls import path
from . import  views
app_name="polls"
urlpatterns = [
    path('',views.Index.as_view(),name="index"),
    path('<int:pk>/',views.Detail.as_view(),name="detail"),
    path('<int:pk>/results/',views.Results.as_view(),name="result"),
    path('<int:question_id>/vote/',views.vote,name="vote"),
]

polls/models.py
from django.db import models
import datetime
from django.utils import timezone

class Question(models.Model):
    question_text=models.CharField(max_length=200)
    pub_date=models.DateTimeField('date published')

    def __str__(self):
        return  self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text=models.CharField(max_length=200)
    votes=models.IntegerField(default=0)

    def __str__(self):
        return  self.choice_text
# Create your models here.

polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from . models import Question
# Create your views here.
class Index(generic.ListView):
    model = Question
    template_name = 'polls/index.html'

    def  get_queryset(self):
        return Question.objects.all()

class Detail(generic.DetailView):
    model=Question
    template_name = 'polls/details.html'

class Results(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected = question.choice_set.get(pk=request.POST['choice'])
    except KeyError:
        return  render(request,'polls/details.html',{'question':question,'error_message':"someting is wrong"})
    else:
        selected.votes+=1
        selected.save()

        return HttpResponseRedirect(reverse('polls:result',args=(question.id,)))

polls/templates/polls/details.html
{% if error_message %}
    <p><strong> {{ error_message }}</strong></p>
{% endif %}
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{%  for i in question_list%}
    <ul>
    <a href="{{ i.id }}/" >{{ i }}</a>
    </ul>
{% endfor %}

polls/templates/polls/results.html
{% for i in question.choice_set.all %}
    <p>no of votes of {{ i }} are {{ i.votes }}</p>
{% endfor %}